### ISSUE TITLE
META-ISSUE

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/EcologicalNetworks.jl#97]
**Semi-curated list of things to do**

These should all be migrated into their own issues when started.

- [ ] Improve speed for unipartite motifs (following bipartite version)
- [ ] Functional roles based on modules (in progress in `feature-modularity-roles`)
- [ ] Additional path algorithms (in progress in `feature-path-algorithms`) see #104 for the issue
- [x] ~~~Fix code for plotting: nodes should have a fixed dimension n, size is number of nodes times n~~~ (**REMOVED**, will be in `EcologicalNetworkPlot`)
- [ ] Trophic species (in progress in `develop`)
    - [x] overlap
    - [x] AJS
    - [x] EAJS
    - [ ] Trophic species aggregation (TBD)
